baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "de"
title = "landmais.ch"

[params]
  author = "Philipp Meyer"
  description = "mais, landmais, hybridmais, hybrid, polenta, landwirtschaft, bio"
