baseurl = "http://www.landmais.ch"
languageCode = "de"
title = "Landmais.ch"

[params]
  author = "Philipp Meyer"
  keywords = "mais, landmais, hybridmais, hybrid, polenta, landwirtschaft, bio"
  analyticsId = "UA-57889358-1"

[taxonomies]
  tag = "tags"